############################################
# 1.Build Stage
############################################
FROM eclipse-temurin:21-jdk AS builder

WORKDIR /app

COPY ../gradlew .
COPY ../gradle gradle
COPY ../build.gradle settings.gradle ./
COPY ../src src

RUN chmod +x gradlew
RUN ./gradlew dependencies --no-daemon
RUN ./gradlew clean build -x test --no-daemon

############################################
# 2.Runtime Stage
############################################
FROM eclipse-temurin:21-jre

WORKDIR /app

RUN mkdir -p /logs/dumps && chmod -R 777 /logs

COPY --from=builder /app/build/libs/*.jar app.jar

EXPOSE 8080

ENV JAVA_OPTS="-XX:InitialRAMPercentage=50.0 \
           -XX:MaxRAMPercentage=50.0 \
           -XX:MetaspaceSize=256M \
           -XX:MaxMetaspaceSize=256M \
           -XX:+UseG1GC \
           -XX:+UseContainerSupport \
           -XX:+HeapDumpOnOutOfMemoryError \
           -XX:HeapDumpPath=/logs/dumps/heapdump.hprof \
           -XX:ErrorFile=/logs/hs_err_pid%p.log \
           -Xlog:gc=info:file=/logs/gc.log:time,uptime:filecount=3,filesize=5M"

ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} \
  -Dspring.config.location=classpath:/,classpath:/config/,classpath:/config/sse/ \
  -Dspring.profiles.active=${SPRING_ACTIVE_PROFILE:-dev} \
  -jar /app/app.jar"]
